version: '3'
services:
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      context: .
    image: guilhermebomfim/api:1.0
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ../src:/code/app
    networks:
      - network-locadora

  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - network-locadora
    expose:
      - 80

  database:
    container_name: database
    image: mysql:8.1
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ../mysql:/var/lib/mysql
    tty: true
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=value
      - MYSQL_DATABASE=value
    networks:
      - network-locadora

networks:
  network-locadora:
    driver: bridge