name: locadora-workflow
on: pull_request

jobs:
  check-app:
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - name: Check code
        uses: actions/checkout@v3
      - name: Commitsar check
        uses: aevea/commitsar
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - name: Test
        run: pytest
  environment-devlopement:
    runs-on: ubuntu-22.04
    steps:
      - name: Enviroment developement
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            app
            nginx
            database